/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reservas;

import javax.swing.JOptionPane;

/**
 *
 * @author chimuelo
 */
public class MenuCita extends javax.swing.JFrame {

    /**
     * Creates new form MenuCita
     */
    SacarCita sacarCita = new SacarCita();
    public MenuCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Sacar_cita = new javax.swing.JButton();
        cancelar_cita = new javax.swing.JButton();
        consultar_cita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sacar_cita.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        Sacar_cita.setText("SACAR CITA");
        Sacar_cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sacar_citaActionPerformed(evt);
            }
        });

        cancelar_cita.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cancelar_cita.setText("CANCELAR CITA");
        cancelar_cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_citaActionPerformed(evt);
            }
        });

        consultar_cita.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        consultar_cita.setText("CONSULTAR CITA");
        consultar_cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_citaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sacar_cita, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(cancelar_cita)
                .addGap(18, 18, 18)
                .addComponent(consultar_cita)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar_cita, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultar_cita, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sacar_cita, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sacar_citaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sacar_citaActionPerformed

        JOptionPane.showMessageDialog(null, "menu para sacar cita");
        sacarCita.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_Sacar_citaActionPerformed

    private void cancelar_citaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_citaActionPerformed
        JOptionPane.showMessageDialog(null, "menu para cancelar cita");
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelar_citaActionPerformed

    private void consultar_citaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_citaActionPerformed

        JOptionPane.showMessageDialog(null, "confirmacion de cancelacion de cita");        // TODO add your handling code here:
    }//GEN-LAST:event_consultar_citaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sacar_cita;
    private javax.swing.JButton cancelar_cita;
    private javax.swing.JButton consultar_cita;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
